// GENERATED by quarry/scripts/import-mozaik-materials.mjs — do not hand-edit.
// Source: Mozaik's own Data/Materials.dat + Textures.dat + TextureGroups.dat.
// Re-run the importer after adding a finish or a board size in Mozaik.
//
// displayName is the material's ReportName with {Texture} substituted — the
// exact string the .opt carries and the file is named after.

export const MOZAIK_CATALOG = [
  {
    "abbr": "19",
    "materialId": "334",
    "textureGroup": "MBD",
    "thickness": 19.05,
    "length": 2770,
    "width": 1550,
    "lengthTrim": 6,
    "widthTrim": 6,
    "additionalSheetSizes": false,
    "displayName": "19_Melamine_Black",
    "label": "19.05mm Melamine — Black",
    "textureId": "13323",
    "textureName": "Black"
  },
  {
    "abbr": "19",
    "materialId": "334",
    "textureGroup": "MBD",
    "thickness": 19.05,
    "length": 2770,
    "width": 1550,
    "lengthTrim": 6,
    "widthTrim": 6,
    "additionalSheetSizes": false,
    "displayName": "19_Melamine_Chocolate",
    "label": "19.05mm Melamine — Chocolate",
    "textureId": "13324",
    "textureName": "Chocolate"
  },
  {
    "abbr": "19",
    "materialId": "334",
    "textureGroup": "MBD",
    "thickness": 19.05,
    "length": 2770,
    "width": 1550,
    "lengthTrim": 6,
    "widthTrim": 6,
    "additionalSheetSizes": false,
    "displayName": "19_Melamine_Gray",
    "label": "19.05mm Melamine — Gray",
    "textureId": "13325",
    "textureName": "Gray"
  },
  {
    "abbr": "19",
    "materialId": "334",
    "textureGroup": "MBD",
    "thickness": 19.05,
    "length": 2770,
    "width": 1550,
    "lengthTrim": 6,
    "widthTrim": 6,
    "additionalSheetSizes": false,
    "displayName": "19_Melamine_Monaco",
    "label": "19.05mm Melamine — Monaco",
    "textureId": "13326",
    "textureName": "Monaco"
  },
  {
    "abbr": "19",
    "materialId": "334",
    "textureGroup": "MBD",
    "thickness": 19.05,
    "length": 2770,
    "width": 1550,
    "lengthTrim": 6,
    "widthTrim": 6,
    "additionalSheetSizes": false,
    "displayName": "19_Melamine_White",
    "label": "19.05mm Melamine — White",
    "textureId": "13327",
    "textureName": "White"
  },
  {
    "abbr": "TOPS",
    "materialId": "339",
    "textureGroup": "",
    "thickness": 19.05,
    "length": 2032,
    "width": 1092.2,
    "lengthTrim": 0,
    "widthTrim": 0,
    "additionalSheetSizes": false,
    "displayName": "TOPS",
    "label": "19.05mm TOPS",
    "textureId": "-1",
    "textureName": ""
  },
  {
    "abbr": "",
    "materialId": "144",
    "textureGroup": "Corian",
    "thickness": 12.7,
    "length": 3022.6,
    "width": 1524,
    "lengthTrim": 3.175,
    "widthTrim": 3.175,
    "additionalSheetSizes": false,
    "displayName": "Corian",
    "label": "12.7mm Corian",
    "textureId": "4255",
    "textureName": "Corian - Abalone"
  }
];
